package connsim

import (
	"fmt"
	"log"
	"math/rand"
	"sync"
	"sync/atomic"
	"time"

	"phalanxsim2/internal/node"
)

// Config controls UDP simulation behavior.
type Config struct {
	MinDelay time.Duration
	MaxDelay time.Duration
	// InterPacketDelay is the fixed spacing between packets generated by a
	// single broadcast call.
	InterPacketDelay time.Duration
	DropRate float64
}

// DefaultConfig returns safe defaults for early small-node experiments.
func DefaultConfig() Config {
	return Config{
		MinDelay: 2 * time.Millisecond,
		MaxDelay: 12 * time.Millisecond,
		InterPacketDelay: 1 * time.Millisecond,
		DropRate: 0,
	}
}

type endpoint struct {
	n        *node.Node
	subnetID uint64
}

// EndpointSnapshot is a serializable endpoint view for UI/debug APIs.
type EndpointSnapshot struct {
	NodeID   node.NodeID `json:"node_id"`
	SubnetID uint64      `json:"subnet_id"`
}

// EdgeSnapshot is an aggregated directed traffic edge.
type EdgeSnapshot struct {
	From       node.NodeID `json:"from"`
	To         node.NodeID `json:"to"`
	SubnetID   uint64      `json:"subnet_id"`
	Kind       string      `json:"kind"`
	Count      int         `json:"count"`
	LastSeenMS int64       `json:"last_seen_ms"`
}

// Snapshot is a full fabric view.
type Snapshot struct {
	Nodes []EndpointSnapshot `json:"nodes"`
	Edges []EdgeSnapshot     `json:"edges"`
}

type edgeKey struct {
	from node.NodeID
	to   node.NodeID
	kind string
}

type edgeStat struct {
	SubnetID uint64
	Count    int
	LastSeen time.Time
}

// Fabric simulates UDP broadcast transport over in-memory node inboxes.
type Fabric struct {
	cfg Config

	rng   *rand.Rand
	rngMu sync.Mutex

	mu      sync.RWMutex
	eps     map[node.NodeID]endpoint
	subnets map[uint64]map[node.NodeID]struct{}
	edges   map[edgeKey]edgeStat

	seq atomic.Uint64
}

// NewFabric creates a new UDP simulation fabric.
func NewFabric(cfg Config, rng *rand.Rand) *Fabric {
	if cfg.MinDelay < 0 {
		cfg.MinDelay = 0
	}
	if cfg.MaxDelay < cfg.MinDelay {
		cfg.MaxDelay = cfg.MinDelay
	}
	if cfg.InterPacketDelay < 0 {
		cfg.InterPacketDelay = 0
	}
	if cfg.DropRate < 0 {
		cfg.DropRate = 0
	}
	if cfg.DropRate > 1 {
		cfg.DropRate = 1
	}
	return &Fabric{
		cfg:     cfg,
		rng:     rng,
		eps:     make(map[node.NodeID]endpoint),
		subnets: make(map[uint64]map[node.NodeID]struct{}),
		edges:   make(map[edgeKey]edgeStat),
	}
}

// RegisterNode registers a node endpoint into a given simulated subnet.
func (f *Fabric) RegisterNode(n *node.Node, subnetID uint64) {
	f.mu.Lock()
	defer f.mu.Unlock()

	f.eps[n.ID] = endpoint{n: n, subnetID: subnetID}
	if f.subnets[subnetID] == nil {
		f.subnets[subnetID] = make(map[node.NodeID]struct{})
	}
	f.subnets[subnetID][n.ID] = struct{}{}
	log.Printf("comp=connsim layer=udp event=register node=%d subnet=%d", n.ID, subnetID)
}

// DeregisterNode removes a node endpoint.
func (f *Fabric) DeregisterNode(id node.NodeID) {
	f.mu.Lock()
	defer f.mu.Unlock()

	ep, ok := f.eps[id]
	if !ok {
		return
	}
	delete(f.eps, id)
	if bucket := f.subnets[ep.subnetID]; bucket != nil {
		delete(bucket, id)
		if len(bucket) == 0 {
			delete(f.subnets, ep.subnetID)
		}
	}
	log.Printf("comp=connsim layer=udp event=deregister node=%d subnet=%d", id, ep.subnetID)
}

// Broadcast sends one simulated UDP datagram to all nodes in sender subnet,
// excluding the sender.
func (f *Fabric) Broadcast(from node.NodeID, kind string, payload []byte, traceID string) int {
	now := time.Now()

	f.mu.RLock()
	src, ok := f.eps[from]
	if !ok {
		f.mu.RUnlock()
		log.Printf("comp=connsim layer=udp event=tx_drop reason=unknown_sender from=%d kind=%s trace=%s", from, kind, traceID)
		return 0
	}
	bucket := f.subnets[src.subnetID]
	ids := make([]node.NodeID, 0, len(bucket))
	for id := range bucket {
		if id == from {
			continue
		}
		ids = append(ids, id)
	}
	// Randomize receiver order inside subnet.
	f.shuffleIDs(ids)
	receivers := make([]endpoint, 0, len(ids))
	for _, id := range ids {
		if ep, exists := f.eps[id]; exists {
			receivers = append(receivers, ep)
		}
	}
	f.mu.RUnlock()

	log.Printf(
		"comp=connsim layer=udp event=broadcast_start from=%d subnet=%d kind=%s trace=%s fanout=%d",
		from, src.subnetID, kind, traceID, len(receivers),
	)

	scheduled := 0
	for _, ep := range receivers {
		if f.shouldDrop() {
			log.Printf(
				"comp=connsim layer=udp event=tx_drop reason=simulated_loss from=%d to=%d subnet=%d kind=%s trace=%s",
				from, ep.n.ID, src.subnetID, kind, traceID,
			)
			continue
		}

		seq := f.seq.Add(1)
		delay := f.sampleDelay() + (time.Duration(scheduled) * f.cfg.InterPacketDelay)
		dgram := node.UDPDatagram{
			Seq:      seq,
			TraceID:  traceID,
			Kind:     kind,
			From:     from,
			To:       ep.n.ID,
			SubnetID: src.subnetID,
			Payload:  append([]byte(nil), payload...),
			SentAt:   now,
		}

		log.Printf(
			"comp=connsim layer=udp event=tx_schedule seq=%d from=%d to=%d subnet=%d delay_ms=%d kind=%s trace=%s",
			seq, from, ep.n.ID, src.subnetID, delay.Milliseconds(), kind, traceID,
		)
		f.recordEdge(from, ep.n.ID, src.subnetID, kind, now)

		target := ep.n
		f.scheduleDatagram(target, from, seq, delay, dgram)
		scheduled++
	}

	log.Printf(
		"comp=connsim layer=udp event=broadcast_done from=%d subnet=%d kind=%s trace=%s scheduled=%d",
		from, src.subnetID, kind, traceID, scheduled,
	)
	return scheduled
}

// Send delivers one simulated UDP packet to a specific node.
func (f *Fabric) Send(from, to node.NodeID, kind string, payload []byte, traceID string) bool {
	now := time.Now()

	f.mu.RLock()
	src, okSrc := f.eps[from]
	dst, okDst := f.eps[to]
	f.mu.RUnlock()

	if !okSrc || !okDst {
		log.Printf(
			"comp=connsim layer=udp event=tx_drop reason=unknown_endpoint from=%d to=%d kind=%s trace=%s",
			from, to, kind, traceID,
		)
		return false
	}
	if f.shouldDrop() {
		log.Printf(
			"comp=connsim layer=udp event=tx_drop reason=simulated_loss from=%d to=%d kind=%s trace=%s",
			from, to, kind, traceID,
		)
		return false
	}

	seq := f.seq.Add(1)
	delay := f.sampleDelay()
	dgram := node.UDPDatagram{
		Seq:      seq,
		TraceID:  traceID,
		Kind:     kind,
		From:     from,
		To:       to,
		SubnetID: src.subnetID,
		Payload:  append([]byte(nil), payload...),
		SentAt:   now,
	}
	f.recordEdge(from, to, src.subnetID, kind, now)

	log.Printf(
		"comp=connsim layer=udp event=unicast_schedule seq=%d from=%d to=%d subnet=%d delay_ms=%d kind=%s trace=%s",
		seq, from, to, src.subnetID, delay.Milliseconds(), kind, traceID,
	)
	f.scheduleDatagram(dst.n, from, seq, delay, dgram)
	return true
}

func (f *Fabric) recordEdge(from, to node.NodeID, subnetID uint64, kind string, ts time.Time) {
	k := edgeKey{from: from, to: to, kind: kind}
	f.mu.Lock()
	defer f.mu.Unlock()
	st := f.edges[k]
	st.SubnetID = subnetID
	st.Count++
	st.LastSeen = ts
	f.edges[k] = st
}

func (f *Fabric) shouldDrop() bool {
	if f.cfg.DropRate <= 0 {
		return false
	}
	f.rngMu.Lock()
	v := f.rng.Float64() < f.cfg.DropRate
	f.rngMu.Unlock()
	return v
}

func (f *Fabric) sampleDelay() time.Duration {
	if f.cfg.MaxDelay <= f.cfg.MinDelay {
		return f.cfg.MinDelay
	}
	f.rngMu.Lock()
	delta := f.rng.Int63n(int64(f.cfg.MaxDelay-f.cfg.MinDelay) + 1)
	f.rngMu.Unlock()
	return f.cfg.MinDelay + time.Duration(delta)
}

func (f *Fabric) scheduleDatagram(target *node.Node, from node.NodeID, seq uint64, delay time.Duration, dgram node.UDPDatagram) {
	time.AfterFunc(delay, func() {
		msg := node.Message{
			Type:    node.MsgUDPDatagram,
			From:    from,
			Payload: dgram,
		}
		select {
		case target.Inbox <- msg:
			log.Printf(
				"comp=connsim layer=udp event=rx_enqueue_ok seq=%d from=%d to=%d subnet=%d kind=%s trace=%s",
				seq, from, target.ID, dgram.SubnetID, dgram.Kind, dgram.TraceID,
			)
		default:
			log.Printf(
				"comp=connsim layer=udp event=rx_enqueue_drop reason=inbox_full seq=%d from=%d to=%d subnet=%d kind=%s trace=%s",
				seq, from, target.ID, dgram.SubnetID, dgram.Kind, dgram.TraceID,
			)
		}
	})
}

func (f *Fabric) shuffleIDs(ids []node.NodeID) {
	if len(ids) < 2 {
		return
	}
	f.rngMu.Lock()
	defer f.rngMu.Unlock()
	f.rng.Shuffle(len(ids), func(i, j int) { ids[i], ids[j] = ids[j], ids[i] })
}

// NodeSubnetForIndex maps a node id to one of subnetCount buckets.
func NodeSubnetForIndex(id node.NodeID, subnetCount int) uint64 {
	if subnetCount <= 1 {
		return 0
	}
	return uint64(id % node.NodeID(subnetCount))
}

// NewTraceID builds a lightweight trace id for logging.
func NewTraceID(prefix string, seq uint64) string {
	return fmt.Sprintf("%s-%06d", prefix, seq)
}

// Snapshot returns a stable copy of fabric endpoints and observed edges.
func (f *Fabric) Snapshot() Snapshot {
	f.mu.RLock()
	defer f.mu.RUnlock()

	out := Snapshot{
		Nodes: make([]EndpointSnapshot, 0, len(f.eps)),
		Edges: make([]EdgeSnapshot, 0, len(f.edges)),
	}

	for id, ep := range f.eps {
		out.Nodes = append(out.Nodes, EndpointSnapshot{
			NodeID:   id,
			SubnetID: ep.subnetID,
		})
	}
	for k, st := range f.edges {
		out.Edges = append(out.Edges, EdgeSnapshot{
			From:       k.from,
			To:         k.to,
			SubnetID:   st.SubnetID,
			Kind:       k.kind,
			Count:      st.Count,
			LastSeenMS: st.LastSeen.UnixMilli(),
		})
	}
	return out
}

// ResetEdges clears all observed edge statistics.
func (f *Fabric) ResetEdges() {
	f.mu.Lock()
	defer f.mu.Unlock()
	f.edges = make(map[edgeKey]edgeStat)
}
